// This file was generated by Firebase Studio.
'use server';
/**
 * @fileOverview Analyzes a product description to identify key ingredients and qualities.
 *
 * - analyzeProductDescription - A function that analyzes the product description.
 * - AnalyzeProductDescriptionInput - The input type for the analyzeProductDescription function.
 * - AnalyzeProductDescriptionOutput - The return type for the analyzeProductDescription function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const AnalyzeProductDescriptionInputSchema = z.object({
  productDescription: z.string().describe('The description of the cosmetic product.'),
});
export type AnalyzeProductDescriptionInput = z.infer<typeof AnalyzeProductDescriptionInputSchema>;

const AnalyzeProductDescriptionOutputSchema = z.object({
  keyIngredients: z.array(z.string()).describe('List of key ingredients identified in the product description.'),
  qualities: z.array(z.string()).describe('List of qualities or benefits described in the product description.'),
});
export type AnalyzeProductDescriptionOutput = z.infer<typeof AnalyzeProductDescriptionOutputSchema>;

export async function analyzeProductDescription(input: AnalyzeProductDescriptionInput): Promise<AnalyzeProductDescriptionOutput> {
  return analyzeProductDescriptionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'analyzeProductDescriptionPrompt',
  input: {
    schema: z.object({
      productDescription: z.string().describe('The description of the cosmetic product.'),
    }),
  },
  output: {
    schema: z.object({
      keyIngredients: z.array(z.string()).describe('List of key ingredients identified in the product description.'),
      qualities: z.array(z.string()).describe('List of qualities or benefits described in the product description.'),
    }),
  },
  prompt: `You are a cosmetic product expert. Analyze the following product description and identify the key ingredients and qualities (benefits) of the product.\n\nProduct Description: {{{productDescription}}}\n\nKey Ingredients:\n- Qualities:\n`,
});

const analyzeProductDescriptionFlow = ai.defineFlow<
  typeof AnalyzeProductDescriptionInputSchema,
  typeof AnalyzeProductDescriptionOutputSchema
>(
  {
    name: 'analyzeProductDescriptionFlow',
    inputSchema: AnalyzeProductDescriptionInputSchema,
    outputSchema: AnalyzeProductDescriptionOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
